on:
  push:
      branches:
        - master
        - main
      paths-ignore:
        - '**/README.md'
        - '**/.github/workflow'
        - '**/.gitignore'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.9
        architecture: "x64"

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile --noconfirm --noupx fabveri.py
    - uses: actions/upload-artifact@v3
      with:
        path: dist/fabveri.exe
